server:
  port: 8081
spring:
  application:
    name: crypto-recommendation
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/crypto?createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}